/* eslint-disable jsx-a11y/media-has-caption */
import { TTrack } from "@/common/types";
import api from "@/utils/axios";
import Head from "next/head";
import { useEffect, useState } from "react";
// import Image from "next/image";
// import styles from "@/styles/Home.module.css";

export default function Home() {
  const [tracks, setTracks] = useState<TTrack[]>([]);

  async function getAllTracks() {
    const res = await api.get("api/tracks");
    setTracks(res.data);
  }

  useEffect(() => {
    getAllTracks();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <h1 className="text-center text-3xl">2006-2007</h1>
        <div className="grid grid-cols-3 gap-3 p-3">
          {tracks.map((track) => (
            <div key={track.id}>
              <div>
                {track.name} {track.album}
              </div>
              <audio controls>
                <source src={track.link} type="audio/wav" />
              </audio>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
