import { TDog } from "@/common/types";
import api from "@/utils/axios";
import Head from "next/head";
import { useEffect, useState } from "react";
// import Image from "next/image";
// import styles from "@/styles/Home.module.css";

export default function Home() {
  const [allDogs, setAllDogs] = useState<TDog[]>([]);

  async function getAllDogs() {
    const res = await api.get("api/dogs");
    setAllDogs(res.data);
  }

  useEffect(() => {
    getAllDogs();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <h1 className="bg-red-800 text-center text-3xl text-emerald-500">Hello World!</h1>
        {allDogs.map((dog) => dog.name)}
      </main>
    </>
  );
}
